export const queryKeys = {
  user: ["user", "me"] as const,
  identity: ["platform", "identity"] as const,
  capabilities: ["platform", "capabilities"] as const,
  flag: (key: string) => ["feature-flag", key] as const,
  onboarding: ["onboarding"] as const,
  dashboard: ["dashboard"] as const,
  profile: ["academic-profile"] as const,
  profileVersions: ["academic-profile", "versions"] as const,
  applications: ["applications"] as const,
  board: ["applications", "board"] as const,
  application: (id: string) => ["applications", id] as const,
  workspace: (id: string) => ["applications", id, "workspace"] as const,
  requirements: (id: string) => ["applications", id, "requirements"] as const,
  tasks: (id: string) => ["applications", id, "tasks"] as const,
  readiness: (id: string) => ["applications", id, "readiness"] as const,
  applicationHistory: (id: string) => ["applications", id, "history"] as const,
  applicationDocuments: (id: string) =>
    ["applications", id, "documents"] as const,
  collaborators: (id: string) => ["applications", id, "collaborators"] as const,
  collaboratorView: (id: string) =>
    ["applications", id, "collaborator-view"] as const,
  eligibility: (id: string) => ["applications", id, "eligibility"] as const,
  eligibilityHistory: (id: string) =>
    ["applications", id, "eligibility", "history"] as const,
  documents: ["academic-documents"] as const,
  document: (id: string) => ["academic-documents", id] as const,
  documentScan: (id: string) => ["academic-documents", id, "scan"] as const,
  documentVersions: (id: string) =>
    ["academic-documents", id, "versions"] as const,
  documentActivity: (id: string) =>
    ["academic-documents", id, "activity"] as const,
  documentLinks: (id: string) => ["academic-documents", id, "links"] as const,
  billing: ["billing"] as const,
  plans: ["billing", "plans"] as const,
  subscription: ["billing", "subscription"] as const,
  entitlements: ["billing", "entitlements"] as const,
  usage: ["billing", "usage"] as const,
  tokenProduct: ["billing", "token-product"] as const,
  purchases: ["billing", "purchases"] as const,
  catalogue: (kind: string, filters: object) =>
    ["catalogue", kind, filters] as const,
  catalogueDetail: (kind: string, id: string) =>
    ["catalogue", kind, id] as const,
  catalogueCountries: ["catalogue", "countries"] as const,
  savedSearches: ["saved-searches"] as const,
  recommendations: ["recommendations"] as const,
  imports: ["opportunity-imports"] as const,
  opportunityImport: (id: string) => ["opportunity-import", id] as const,
  writing: ["writing"] as const,
  writingDocument: (id: string) => ["writing", id] as const,
  generationRuns: (id: string) => ["writing", id, "generation-runs"] as const,
  comments: (id: string) => ["writing", id, "comments"] as const,
  shareLinks: (id: string) => ["writing", id, "share-links"] as const,
  stories: (filters: object = {}) => ["stories", filters] as const,
  storyUsage: (id: string) => ["stories", id, "usage"] as const,
  entityUsage: (entityType: string, entityId: string) =>
    ["usage", entityType, entityId] as const,
  references: (status = "") => ["references", { status }] as const,
  reference: (id: string) => ["references", id] as const,
  referenceEvents: (id: string) => ["references", id, "events"] as const,
  interviews: ["interviews"] as const,
  interview: (id: string) => ["interviews", id] as const,
  interviewTurns: (id: string) => ["interviews", id, "turns"] as const,
  interviewReport: (id: string) => ["interviews", id, "report"] as const,
  notifications: (unreadOnly = false) =>
    ["notifications", { unreadOnly }] as const,
  unreadNotifications: ["notifications", "unread-count"] as const,
  notificationPreferences: ["notification-preferences"] as const,
  reminders: (filters: object = {}) => ["reminders", filters] as const,
  admin: (surface: string, filters: object = {}) =>
    ["admin", surface, filters] as const,
};
