import { useState } from "react";
import { useInfiniteQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import type { components } from "../../generated/api/schema";
import { remindersApi } from "../../lib/api/phase3";
import { queryKeys } from "../../lib/api/queryKeys";
import { useSession } from "../../lib/auth/session";
type S = components["schemas"];

export function RemindersPage() {
  const timezone = useSession((state) => state.user?.timezone) || "UTC"; const qc = useQueryClient(); const [status, setStatus] = useState(""); const [aggregateType, setAggregateType] = useState(""); const [feedUrl, setFeedUrl] = useState(""); const filters = { status, aggregateType };
  const list = useInfiniteQuery({ queryKey: queryKeys.reminders(filters), queryFn: ({ pageParam }) => remindersApi.list({ status: status || undefined, aggregateType: aggregateType || undefined, cursor: pageParam }), initialPageParam: null as string | null, getNextPageParam: (page) => page.next_cursor ?? undefined });
  const refresh = () => void qc.invalidateQueries({ queryKey: ["reminders"] });
  const remove = useMutation({ mutationFn: remindersApi.remove, onSuccess: refresh }); const snooze = useMutation({ mutationFn: ({ id, until }: { id: string; until: string }) => remindersApi.snooze(id, { until }), onSuccess: refresh });
  const items = list.data?.pages.flatMap((page) => page.items) ?? [];
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await remindersApi.create({ mutation_id: crypto.randomUUID(), aggregate_type: data.get("aggregate_type") as S["ReminderCreate"]["aggregate_type"], aggregate_id: String(data.get("aggregate_id")) || null, title: String(data.get("title")), notes: String(data.get("notes")) || null, scheduled_at: new Date(String(data.get("scheduled_at"))).toISOString(), timezone, recurrence: data.get("recurrence") as S["ReminderCreate"]["recurrence"], channel: data.get("channel") as S["ReminderCreate"]["channel"] }); event.currentTarget.reset(); refresh(); }
  async function edit(item: (typeof items)[number]) { const title = prompt("Reminder title", item.title); if (title === null) return; await remindersApi.update(item.id, { expected_version: item.version, title }); refresh(); }
  async function createFeed() { const response = await remindersApi.createFeed(); setFeedUrl(response.feed_url); }
  return <div className="page"><header className="page-heading"><div><h1>Reminders</h1><p>Schedule follow-ups in {timezone}. Dates are stored with your profile timezone.</p></div></header>
    <section className="phase3-panel"><h2>New reminder</h2><form className="reminder-form" onSubmit={create}><label>Title<input name="title" required /></label><label>Context<select name="aggregate_type">{["application","requirement","task","reference","interview","custom"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Context ID <span className="muted">(optional)</span><input name="aggregate_id" /></label><label>When<input name="scheduled_at" type="datetime-local" required /></label><label>Repeat<select name="recurrence"><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Channel<select name="channel"><option value="in_app">In app</option><option value="email">Email</option></select></label><label className="wide">Notes<textarea name="notes" /></label><button className="primary">Create reminder</button></form></section>
    <div className="phase3-filters"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All</option><option value="scheduled">Scheduled</option><option value="cancelled">Cancelled</option></select></label><label>Context<select value={aggregateType} onChange={(event) => setAggregateType(event.target.value)}><option value="">All</option>{["application","requirement","task","reference","interview","custom"].map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <div className="phase3-card-list">{items.map((item) => <article className="phase3-card" key={item.id}><span className="status-pill">{item.status.replaceAll("_", " ")}</span><h2>{item.title}</h2><p>{item.notes || `${item.aggregate_type} reminder`}</p><time dateTime={item.scheduled_at}>{new Date(item.scheduled_at).toLocaleString([], { timeZone: item.timezone })}</time><div className="phase3-actions"><button onClick={() => edit(item)}>Edit</button><button onClick={() => { const input = prompt("Snooze until (for example 2026-07-20 09:00)"); if (input) snooze.mutate({ id: item.id, until: new Date(input).toISOString() }); }}>Snooze</button><button className="danger" onClick={() => confirm("Delete this reminder?") && remove.mutate(item.id)}>Delete</button></div></article>)}</div>{list.hasNextPage ? <button className="load-more" onClick={() => list.fetchNextPage()}>Load more</button> : null}
    <section className="phase3-panel"><h2>Calendar feed</h2><p>Create a private subscription URL for your calendar. Treat it like a password.</p>{feedUrl ? <div className="calendar-token"><input readOnly value={feedUrl} aria-label="Private calendar feed URL" /><button className="secondary-action" onClick={() => navigator.clipboard.writeText(feedUrl)}>Copy</button></div> : null}<div className="phase3-actions">{feedUrl ? null : <button className="primary" onClick={createFeed}>Create calendar feed</button>}<button className="secondary-action danger" onClick={() => confirm("Revoke the current calendar feed URL?") && remindersApi.revokeFeed().then(() => setFeedUrl(""))}>Revoke feed</button></div></section>
  </div>;
}
