import { useState } from "react";
import { useInfiniteQuery, useQuery, useQueryClient } from "@tanstack/react-query";
import { Navigate } from "react-router-dom";
import { adminApi } from "../../lib/api/phase3";
import { useSession } from "../../lib/auth/session";
import { usePromptDialog } from "../../components/PromptDialog";

export function AdminLaunchPage() {
  const requestText = usePromptDialog();
  const admin = useSession((state) => state.user?.is_admin); const qc = useQueryClient(); const enabled = Boolean(admin); const [operationStatus, setOperationStatus] = useState(""); const [catalogueKind, setCatalogueKind] = useState("institution"); const [user, setUser] = useState<Awaited<ReturnType<typeof adminApi.userSearch>> | null>(null); const [referenceId, setReferenceId] = useState("");
  const readiness = useQuery({ queryKey: ["admin", "readiness"], queryFn: adminApi.readiness, enabled, retry: false });
  const gates = useQuery({ queryKey: ["admin", "gates"], queryFn: adminApi.gates, enabled, retry: false });
  const flags = useQuery({ queryKey: ["admin", "flags"], queryFn: adminApi.flags, enabled, retry: false });
  const operations = useInfiniteQuery({ queryKey: ["admin", "operations", operationStatus], queryFn: ({ pageParam }) => adminApi.operations({ status: operationStatus || undefined, cursor: pageParam }), initialPageParam: null as string | null, getNextPageParam: (page) => page.next_cursor ?? undefined, enabled, retry: false });
  const catalogue = useInfiniteQuery({ queryKey: ["admin", "catalogue", catalogueKind], queryFn: ({ pageParam }) => adminApi.pendingCatalogue(catalogueKind, pageParam), initialPageParam: null as string | null, getNextPageParam: (page) => page.next_cursor ?? undefined, enabled, retry: false });
  const referenceEvents = useQuery({ queryKey: ["admin", "reference-events", referenceId], queryFn: () => adminApi.referenceEvents(referenceId), enabled: enabled && Boolean(referenceId), retry: false });
  if (!admin) return <Navigate to="/app/dashboard" replace />;
  const operationItems = operations.data?.pages.flatMap((page) => page.items) ?? []; const catalogueItems = catalogue.data?.pages.flatMap((page) => page.items) ?? [];
  return <div className="page admin-launch"><header className="page-heading"><div><h1>Operations console</h1><p>Lifecycle metadata only. Backend authorization remains authoritative; sensitive application content is never rendered here.</p></div></header>
    <section className="phase3-panel"><h2>Launch readiness</h2><SafeRecord value={readiness.data ?? { status: "Loading" }} /><h3>Launch gates</h3>{gates.data?.map((gate, index) => { const value = gate as Record<string, unknown>; return <form className="gate" key={String(value.key ?? index)} onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (!confirm(`Update launch gate ${String(value.key)}?`)) return; await adminApi.updateGate(String(value.key), { status: data.get("status") as "pending", evidence_reference: String(data.get("evidence")) || null, notes: String(data.get("notes")) || null }); void gates.refetch(); }}><strong>{String(value.key ?? "Gate")}</strong><select name="status" defaultValue={String(value.status ?? "pending")}><option>pending</option><option>passed</option><option>failed</option><option>waived</option></select><input name="evidence" placeholder="Evidence reference" /><input name="notes" placeholder="Audit note" /><button>Update gate</button></form>; })}</section>
    <section className="phase3-panel"><h2>Feature flags</h2><div className="admin-flag-list">{flags.data?.map((flag) => <form key={flag.key} onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const kill = data.get("kill") === "on"; if ((kill || flag.enabled) && !confirm(`Apply operational change to ${flag.key}?`)) return; await adminApi.updateFlag(flag.key, { enabled: data.get("enabled") === "on", rollout_percentage: Number(data.get("rollout")), cohorts: String(data.get("cohorts")).split(",").map((x) => x.trim()).filter(Boolean), kill_switch: kill, reason: String(data.get("reason")) }); void qc.invalidateQueries({ queryKey: ["admin", "flags"] }); }}><strong>{flag.key}</strong><label><input name="enabled" type="checkbox" defaultChecked={flag.enabled} /> Enabled</label><label>Rollout <input name="rollout" type="number" min="0" max="100" defaultValue={flag.rollout_percentage} /></label><label>Cohorts <input name="cohorts" defaultValue={flag.cohorts.join(", ")} /></label><label>Reason <input name="reason" required /></label><label><input name="kill" type="checkbox" defaultChecked={flag.kill_switch} /> Kill switch</label><button>Save</button></form>)}</div></section>
    <section className="phase3-panel"><div className="phase3-section-head"><div><h2>Operations</h2><p>Retry or cancel lifecycle jobs without inspecting their content.</p></div><label>Status<input value={operationStatus} onChange={(event) => setOperationStatus(event.target.value)} placeholder="failed" /></label></div><div className="admin-operation-list">{operationItems.map((item) => <article key={item.id}><span className="status-pill">{item.status}</span><strong>{item.type.replaceAll("_", " ")}</strong><small>User {item.user_id}</small><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleString()}</time><div><button onClick={async () => { if (confirm("Retry this operation?")) { await adminApi.retryOperation(item.id); void operations.refetch(); } }}>Retry</button><button className="danger" onClick={async () => { if (confirm("Cancel this operation?")) { await adminApi.cancelOperation(item.id); void operations.refetch(); } }}>Cancel</button></div></article>)}</div>{operations.hasNextPage ? <button onClick={() => operations.fetchNextPage()}>Load more operations</button> : null}<form className="admin-inline-form" onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (!confirm("Redrive messages from this dead-letter queue?")) return; await adminApi.redrive(String(data.get("queue")), { max_messages: Number(data.get("max")), reason: String(data.get("reason")) }); event.currentTarget.reset(); }}><h3>Dead-letter redrive</h3><input name="queue" required placeholder="Queue name" /><input name="max" type="number" min="1" max="100" defaultValue="10" /><input name="reason" required placeholder="Operational reason" /><button>Redrive</button></form></section>
    <section className="phase3-panel"><h2>User support lookup</h2><form className="admin-inline-form" onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setUser(await adminApi.userSearch(String(data.get("email")) || undefined, String(data.get("user_id")) || undefined)); }}><input name="email" type="email" placeholder="Email" /><span>or</span><input name="user_id" placeholder="User ID" /><button>Search</button></form>{user ? <div><SafeRecord value={user} /><button onClick={async () => alert(JSON.stringify(await adminApi.userEntitlement(user.id), null, 2))}>View entitlement metadata</button><button onClick={async () => alert(JSON.stringify(await adminApi.userUsage(user.id), null, 2))}>View usage metadata</button></div> : null}</section>
    <section className="phase3-panel"><div className="phase3-section-head"><div><h2>Catalogue moderation</h2><p>Review community-submitted catalogue records.</p></div><select value={catalogueKind} onChange={(event) => setCatalogueKind(event.target.value)}><option>institution</option><option>programme</option><option>scholarship</option></select></div>{catalogueItems.map((item) => <article className="moderation-row" key={item.id}><div><strong>{item.name}</strong><small>{item.source_url || "No source URL"}</small></div><button onClick={async () => { if (confirm(`Approve ${item.name}?`)) { await adminApi.approveCatalogue(catalogueKind, item.id); void catalogue.refetch(); } }}>Approve</button><button className="danger" onClick={async () => { const reason = await requestText({ title: "Reject catalogue record", label: "Rejection reason", required: true, multiline: true, submitLabel: "Reject" }); if (reason) { await adminApi.rejectCatalogue(catalogueKind, item.id, { reason }); void catalogue.refetch(); } }}>Reject</button><button onClick={async () => { const target_id = await requestText({ title: "Merge catalogue record", label: "Target record ID", required: true, submitLabel: "Continue" }); const reason = target_id && await requestText({ title: "Confirm merge details", label: "Merge reason", required: true, multiline: true, submitLabel: "Continue" }); if (target_id && reason && confirm("Merge this record?")) { await adminApi.mergeCatalogue(catalogueKind, item.id, { target_id, reason }); void catalogue.refetch(); } }}>Merge</button></article>)}</section>
    <section className="phase3-panel"><h2>Reference event lookup</h2><form className="admin-inline-form" onSubmit={(event) => { event.preventDefault(); setReferenceId(String(new FormData(event.currentTarget).get("reference_id"))); }}><input name="reference_id" required placeholder="Reference ID" /><button>Load event metadata</button></form>{referenceEvents.data ? <SafeRecord value={{ items: referenceEvents.data.items, has_more: referenceEvents.data.has_more }} /> : null}</section>
    <section className="phase3-panel"><h2>Reminder scheduler</h2><p>Manual fallback for the due-reminder worker. Use only during an incident.</p><button className="danger" onClick={() => confirm("Run due reminders now? This can send user notifications.") && adminApi.runDueReminders()}>Run due reminders</button></section>
  </div>;
}

function SafeRecord({ value }: { value: Record<string, unknown> }) { return <dl className="phase3-object">{Object.entries(value).filter(([key]) => !/(token|code|content|payload|text)/i.test(key)).map(([key, item]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{typeof item === "string" || typeof item === "number" || typeof item === "boolean" ? String(item) : JSON.stringify(item)}</dd></div>)}</dl>; }
